### ISSUE TITLE
Help in getting everything working

### ISSUE THREAD

**Issue by orangethewell** [BeyondMagic/MaGiCK#2]
Hello! i'm the guy from Reddit. Sooo the progress I made is making DWM actually run. I was looking for some of the patches for it and I was trying to add a patch to make a autostart script, but until now, I couldn't make it work :[

It gives a error probably because the branch being up-to-date. And I couldn't get the lemonbars working, it says `Can't obtain RESOURCE_MANAGER.` Sorry for bothering about everything, because I really wanted to get challenged to do it and have a cool DE like the print you showed in the Subreddit :>

**Comment by BeyondMagic** [comment]
Were you able to make a `dwm.destkop` using the [wiki page](https://wiki.archlinux.org/title/Display_manager) I passed to you so that the KDE login manager can see it in the list of sessions when you boot your machine? Or are you planning to remove KDE completely? I am asking this because the session is supposed to auto-start programs after the login, not the `window manager` itself.

And are using my DWM build or yours? Mine is preferable because the position of bars are actually set by dwm.

---

### Bars

As I believe you already have DWM running, let's continue:

If you go to lemonbars scripts, there are actually some dependencies that you need so you can use it, as it says there, but as I want to make this process easier, let's start with the following commands:

``` bash
$ cd "$HOME"
$ mkdir -p 
$ cd git
$ git clone https://github.com/BeyondMagic/scripts/
$ mkdir -p suckless
$ cd suckless
$ git clone https://github.com/beyondmagic/mod-xnotify xnotify
$ cd xnotify
$ sudo make install clean
$ cd ..
$ git clone https://github.com/BeyondMagic/heartbar lemonbar
$ cd lemonbar
$ sudo make install clean
$ cd ..
$ touch "$HOME/.Xresources"
```

Add the following to `~/.Xresources`

```xdefaults
bars.font.normal             : Noto Sans CJK JP Medium:antialias=true:size=10
bars.font.bold               : Noto Sans CJK JP Black:style=Black,Regular:antialias=true:size=10
bars.font.emoji              : NotoEmoji Nerd Font:antialias=true:size=10.3
bars.font.material           : Material\\-Design\\-Iconic\\-Font:style=Design-Iconic-Font
bars.top.geometry            : 1400x19+20+10
bars.bottom.geometry         : 1400x19+20+10
bars.preview.geometry        : 260x164+60+688
bars.preview.title           : preview_dwm
bars.name0                   : 狐 🦊 Kitsune
bars.name1                   : なんでも
bars.name2                   : ターミナル
bars.name3                   : 編集者 📖 Henshū-sha
bars.name4                   : Zシェル
bars.name5                   : バイノキュラス
bars.name6                   : ポップコーン
bars.name7                   : ブレイクダンス
bars.name8                   : 友達 💙 Tomodachi
bars.name9                   : すべての
bars.songs.icon.paused       : " [  •́ ◇ •̀  ] "
bars.songs.extra.limit       : 35
bars.songs.title.limit       : 20
bars.songs.notification.time : 550
bars.tags.selected           : 
bars.tags.selected.occupied  : 
bars.tags.unselect           : 
bars.tags.unselect.occupied  : 
bars.separator1              : 
bars.separator2              : 
bars.separator3              : 
bars.separator4              : 
bars.bg : #990A0C11
bars.fg : #ffffff

bars.bottom.nickname                 : yourname %{T3}%{F#7EABF8}%{T2}%{F#FFFFFF} something
bars.bottom.recording.fg             : #FFFfff
bars.bottom.tags.bg                  : #0A0C11
bars.bottom.tags.selected.fg         : #ffffff
bars.bottom.tags.selected.occupied   : #ffffff
bars.bottom.tags.unselected.fg       : #696969
bars.bottom.tags.unselected.occupied : #82CDD2
bars.bottom.tags.unselected.all      : #444444
bars.bottom.layout.fg                : #0A0C11
bars.bottom.layout.bg                : #ffffff
bars.bottom.titles.title             : #ffffff
bars.bottom.titles.icon              : #698B2F
bars.bottom.memory.colour            : #ffffff
bars.bottom.memory.bar               : #666666

bars.top.sound.icon.on     : #ffffff
bars.top.sound.icon.off    : #525659
bars.top.sound.bar.on      : #ffffff
bars.top.sound.bar.off     : #000000
bars.top.clock.fg          : #123456
bars.top.clock.bg          : #ecf3fa
bars.top.clock.fbg         : #ffffff
bars.top.clock.ffg         : #bdcdd7
bars.top.sensors.affix.fg  : #FFFFFF
bars.top.sensors.affix.bg  : #2B2B2B
bars.top.sensors.low.fg    : #0D2331
bars.top.sensors.low.bg    : #87C7E4
bars.top.sensors.normal.fg : #0D2331
bars.top.sensors.normal.bg : #BDCDD7
bars.top.sensors.medium.fg : #340010
bars.top.sensors.medium.bg : #FAFBC2
bars.top.sensors.high.fg   : #0D2331
bars.top.sensors.high.bg   : #FF4464
bars.top.songs.before      : #2b2b2b
bars.top.songs.icon        : #000000
bars.top.songs.song        : #000000
bars.top.songs.song.first  : #FE4656
bars.top.songs.song.second : #E4F2FF
bars.top.songs.icon.name   : #FFFFFF
bars.top.songs.neighbours  : #666666
bars.top.power.fg          : #fafafa
bars.top.power.bg          : #c92430
```

Install the following packages with either **paru** or **yay** (or any other similar program):

``` bash
$ paru -S xgetres mpd mpc notify-send.sh lm_sensors xdotool dash doas
$ yay -S xgetres mpd mpc notify-send.sh lm_sensors xdotool dash doas
```

Create and add the following in `/etc/doas.conf` with your username and/or group:

```
permit persist :YOUR_USERNAME_GROUP
permit nopass :YOUR_USERNAME_GROUP cmd zzz
permit nopass :YOUR_USERNAME_GROUP cmd halt
permit nopass :YOUR_USERNAME_GROUP cmd shutdown
```

Now for the music server, I am using [mpd](https://wiki.archlinux.org/title/Music_Player_Daemon) as the server to load music and `mpc` to get/send information. To create the configuration, run:

``` bash
$ mkdir -p "$HOME/.config/mpd"
$ touch "$HOME/.config/mpd/mpd.conf"
```

Now add this but changing the paths to your music folder, if you don't have, just create one somewhere.

```
music_directory "/home/YOUR_USERNAME/music//"
playlist_directory "/home/YOUR_USERNAME/music/playlists"
db_file "/home/YOUR_USERNAME/.config/mpd/mpd.db"
log_file "/home/YOUR_USERNAME/.config/mpd/mpd.log"
pid_file "/home/YOUR_USERNAME/.config/mpd/mpd.pid"
state_file "/home/YOUR_USERNAME/.config/mpd/mpdstate"

audio_output {
  type "pulse"
  name "pulse audio"
}

port "6600"
```

Run `mpd` to ensure everything is working with:

``` bash
$ mpd & disown
```

Now try to start the lemonbars first by this command;

``` bash
$ ~/git/scripts/bars/lemonbars
```

It should say some few things, but it should open two bars at the bottom and top. If fine, just run:

``` bash
$ ~/git/scripts/bars/modules
```

Again, it should be just fine with a few messages, now close the terminal and just let it go.

---

### Keybinds

As you may have know for now, my DWM build does not have any keybinds by default for external programs, so for that, I could recommend you `xbindkeys`, something along those lines to open **terminal** and **dmenu**:

``` bash
$ pacman -S xbindkeys 
$ touch "$HOME/.xbindkeysrc"
```

`.xbindkeysrc`

```zsh
# Simple terminal
"st"
  m:0x50 + c:36
    Super + Return

# Simple terminal with float status
"st_float"
    m:0x50 + c:22
      Super + Back

# Run DMENU to open a program
"dmenu_run -r -i"
  m:0x50 + c:40
    Super + d
```

---

Those are the most important steps for the complete lemonbar and keybinds setup, I believe you can actually work a lot from there, if you have errors, you can always search them to learn more and, well, faster than asking me. But if that's no help, contact again in this issue.

**Comment by orangethewell** [comment]
I tried to install noto-fonts-jp package (noto-fonts-cjk-jp-vf) and the download don't finish well :/

I even tried to download the noto package with wget but it when it reaches the 1,60/1,80 GB, it's stops and restart the download. Is it really needed and have another package or it's disposable?

In addiction, I installed your version of DWM and added it on LightDM, after I patched it on hand with the autostart script, I don't know about the other way to do it, anyway I would like to open these programs (like feh, picom and others) only with DWM, if I want to install another DE or WM next to DWM

Error: `2021-11-21 15:37:45 (1,37 MB/s) - Erro de leitura no byte 1950651344 (A requisição é inválido.).Tentando novamente.` >> `2021-11-21 15:37:45 (1,37 MB/s) - Read error in the 1950651344 byte (The request is invalid.). Trying again.`

**Comment by BeyondMagic** [comment]
> I tried to install noto-fonts-jp package (noto-fonts-cjk-jp-vf) and the download don't finish well :/. Is it really needed and have another package or it's disposable?

No, none of the fonts are, but I guess it would make it faster to test it with everything already working fine without editing a lot of things. If you were able to install the other fonts, in the XResources file that I quoted before, just change this value to any [other font](https://wiki.archlinux.org/title/fonts) you want to use:

**Comment by orangethewell** [comment]
Hello! I'm back after so long... Sorry, I tried the first time and got upset with trying to reproduce the config. But now I'm back with most everything working! I saw that you removed the lemonbar that you used in scripts, and now my goal is to get lemonbar or any bar program you are using (since it doesn't look the same). Anyways, I configured the terminal, the picom (which I had some problems cause it seems that the configuration you used doesn't support rounded corners, and for some reason my picom have a problem with glx context, but it works well with no experimental backends and kernel blur method) and I was waiting to ask something to know how could I reproduce the bars config, since it is what is missing for now.

Thank you for creating all these configurations until now :) (and now I'm trying to use neovim, since it's looks really cool)

**Comment by BeyondMagic** [comment]
Hello again, the bar is [EWW](https://github.com/elkowar/eww), you can see the [config here](https://github.com/BeyondMagic/MaGiCK/tree/main/.config/eww). I just updated with the latest versions.

**Comment by orangethewell** [comment]
Okay! Almost everything is working! There is just tree things that i'm missing, and a extra that I saw on your screenshots:

### Rofi Menu
I tried a little to copy some random files but it didn't worked, it's says "Too much files"

### Shutdown button (?)
This is a problem that I'm handling since lemonbars and I couldn't make it work. I don't even now if you made something about shutdowning in eww, but I just set it there if there's something to do with it

### Notifying
I couldn't configure notifying with previous scripts that you saved in Creamberry repo, when I tried it was saying that I should configure a service to it

### The kanji names of days of week
I saw that on the screenshot and I found it really cute!! How you made this? Did you changed the locations or is something related to EWW?

Anyways, thanks a lot for the work you made! Good work! :D

**Comment by BeyondMagic** [comment]
> **Rofi Menu**

Yes, sorry about that, the configuration of **rofi** is now located on the `~/.config/` folder, [here](https://github.com/BeyondMagic/MaGiCK/tree/main/.config/rofi). It is used with the current command: `rofi -theme ~/.config/rofi/themes/launcher.rasi -show drun -hover-select -terminal flarity -m 'Mouse1'`.

`Mouse1` because I use the mouse on the left.

> **Shutdown button**

I am using [91menu](https://github.com/LoupLobet/91menu) with this [script](https://github.com/BeyondMagic/creamberry/blob/master/path/desktop_root_click), but I plan to change to something more robust soon, e.j. [xmenu](https://github.com/phillbush/xmenu).

...

> **Kanji**

The entire setup is settled on the Japanese locale, you first have to generate them [per wiki](https://wiki.archlinux.org/title/locale). E.j. in `/etc/locale.gen` uncomment the following:

```
# ....
ja_JP.EUC-JP EUC-JP  
ja_JP.UTF-8 UTF-8  
# ....
```

After this, you can start using `LANG=ja_JP.UTF-8 <command>` to launch most programs and receive the information in Japanese (if supported) -- and in the case of the `date` command, use instead `LC_TIME=ja_JP.UTF-8 date`

I've updated it in the latest few weeks the configuration as well and forgot to update it in here, but here's the current look:

![image](https://user-images.githubusercontent.com/51831435/156256051-df8558b0-bc7a-4894-bc84-2df4abaa3e01.png)

**Comment by orangethewell** [comment]
I'm having some performance issues with eww bars, using all scripts made my 4-core cpu go to 100% usage. There's a way to avoid it?

**Comment by BeyondMagic** [comment]
Disable the EWW bars for now. Some of the scripts is creating forks of
itself. Also, I recommend learning way more about shell scripting and EWW.

All of them are not finished yet, and I really just keep updating them on
my free time.

—
